<?php
$txt = "Maka :";
$a	 = "A. SILOGISME KATEGORIK";
$b	 = "Logika :";
$c 	 = ": p -> q";
$d 	 = ": q";
$e   = "=================================================";
$f   = "Kesimpulan: p";
$g   = "Sehingga :";
$h   = ": mahasiswa butuh pembelajaran, Julius belajar";
$i	 = ": mahasiswa butuh pembelajaran";
$j   = "=================================================";
$k   = "Kesimpulan : maka Julius butuh pembelajaran";
$l   = "B. SILOGISME DISJUNGTIF";
$m   = "Logika";
$n   = ": (p v q)^ p -> ~q";
$o   = ": ~q";
$p   = "=================================================";
$q   = "Kesimpulan: ~q";
$r   = "Sehingga :";
$s   = ": mahasiswa butuh pembelajaran, Julius belajar";
$t   = ": ternyata Julius tidak belajar";
$u   = "=================================================";
$v   = "Kesimpulan : jadi pasti Julius tidak belajar";
$w   = "C. DILEMA";
$x   = "Logika :";
$y   = ": {(p -> q)^((r -> q)}^(p -> r)";
$z  = "q";
$ab  = "=================================================";
$ac  = "Kesimpulan: p";
$ad  = "Sehingga :";
$ae  = ": jika mahasiswa butuh pembelajaran, dan Julius butuh belajar";
$af  = ": mahasiswa atau Julius butuh pembelajaran";
$ag  = "Kesimpulan : maka mahasiswa dan Julius belajar";
$ah  = "D. PREDIKAT LOGIS";
$ai  = "Logika :";
$aj  = ": p -> q";
$ak  = ": ~q";
$al  = "=================================================";
$am  = "Kesimpulan: ~p";
$an  = "Sehingga :";
$ao  = ": mahasiswa butuh pembelajaran, Julius belajar";
$ap  = ": Julius dan Julius belajar";
$aq  = "=================================================";
$ar  = "Kesimpulan : maka mahasiswa dan Julius itu butuh belajar";

    echo $txt;
	echo "<br>";
	echo $a;
	echo "<br>";
	echo $b;
	echo "<br>";
	echo $c;
	echo "<br>";
	echo $d;
	echo "<br>";
	echo $e;
	echo "<br>";
	echo $f;
	echo "<br>";
	echo $g;
	echo "<br>";
	echo $h;
	echo "<br>";
	echo $i;
	echo "<br>";
	echo $j;
	echo "<br>";
	echo $k;
	echo "<br>";
	echo $l;
	echo "<br>";
	echo $m;
	echo "<br>";
	echo $n;
	echo "<br>";
	echo $o;
	echo "<br>";
	echo $p;
	echo "<br>";
	echo $q;
	echo "<br>";
	echo $r;
	echo "<br>";
	echo $s;
	echo "<br>";
	echo $t;
	echo "<br>";
	echo $u;
	echo "<br>";
	echo $v;
	echo "<br>";
	echo $w;
	echo "<br>";
	echo $x;
	echo "<br>";
	echo $y;
	echo "<br>";
	echo $z;
	echo "<br>";
	echo $ab;
	echo "<br>";
	echo $ac;
	echo "<br>";
	echo $ad;
	echo "<br>";
	echo $ae;
	echo "<br>";
	echo $af;
	echo "<br>";
	echo $ag;
	echo "<br>";
	echo $ah;
	echo "<br>";
	echo $ai;
	echo "<br>";
	echo $aj;
	echo "<br>";
	echo $ak;
	echo "<br>";
	echo $al;
	echo "<br>";
	echo $am;
	echo "<br>";
	echo $an;
	echo "<br>";
	echo $ao;
	echo "<br>";
	echo $ap;
	echo "<br>";
	echo $aq;
	echo "<br>";
	echo $ar;
?>

elseif ($ditanya=="silogismedisjungtif") {
echo "<b>"; echo "Silogisme Disjungtif"; echo "</b>";
echo "<br>"; echo "Logika :";
echo "<center>"; echo "(p v q)^ p -> ~q"; echo "</center>";
echo "<center>"; echo "~q"; echo "</center>";
echo "<center>"; echo "================================"; echo "</center>";
echo "Kesimpulan :"; echo "<center>"; echo "~q"; echo "</center>";
echo "<br>"; echo "Sehingga :";

echo "<center>"; echo $sp; echo "&nbsp"; echo $sq; echo ","; echo "&nbsp"; echo $p; echo "&nbsp"; echo $q; echo"</center>"; 
echo "<br>";
echo "<center>"; echo "ternyata"; echo "&nbsp"; echo $p; echo "&nbsp"; echo "tidak"; echo $q; echo "</center>";
echo "<center>"; echo "================================"; echo "</center>";
echo "<left>"; echo "Kesimpulan :"; echo "</left>";
echo "<center>"; echo "jadi pasti"; echo "&nbsp"; echo $p; echo "&nbsp"; echo "tidak"; echo "&nbsp"; echo $q;
	}
	elseif ($ditanya=="dilema") {
echo "<b>"; echo "Dilema"; echo "</b>";
echo "<br>"; echo "Logika :";
echo "<center>"; echo "{ (p -> q)^{(r -> q) }^(p -> r)"; echo "</center>";
echo "<center>"; echo "q"; echo "</center>";
echo "<center>"; echo "================================"; echo "</center>";
echo "Kesimpulan :"; echo "<center>"; echo "p"; echo "</center>";
echo "<br>"; echo "Sehingga :";
echo "<center>"; echo "jika"; echo "&nbsp"; echo $sp; echo "&nbsp"; echo $sq; echo ","; echo"dan"; echo "&nbsp"; echo $p; echo "&nbsp"; echo"butuh"; echo $q; echo"</center>"; 
echo "<br>";
echo "<center>"; echo $sp; echo "&nbsp"; echo "atau"; echo $p; echo "&nbsp"; echo $sq; echo "</center>";
echo "<center>"; echo "================================"; echo "</center>";
echo "<left>"; echo "Kesimpulan :"; echo "</left>";
echo "<center>"; echo "maka"; echo "&nbsp";
    }
    elseif ($ditanya=="predikatlogis") {
echo "<b>"; echo "Predikat Logis"; echo "</b>";
echo "<br>"; echo "Logika :";
echo "<center>"; echo "p -> q"; echo "</center>";
echo "<center>"; echo "~q"; echo "</center>";
echo "<center>"; echo "================================"; echo "</center>";
echo "Kesimpulan :"; echo "<center>"; echo "~p"; echo "</center>";
echo "<br>"; echo "Sehingga :";
echo "<center>"; echo $sp; echo "&nbsp"; echo $sq; echo ","; echo $p; echo "&nbsp"; echo $q; echo"</center>"; 
echo "<br>";
echo "<center>"; echo $p; echo "&nbsp"; echo "dan"; echo "&nbsp"; echo $p; echo "&nbsp"; echo $q; echo "</center>";
echo "<center>"; echo "================================"; echo "</center>";
echo "<left>"; echo "Kesimpulan :"; echo "</left>";
echo "<center>"; echo "maka"; echo "&nbsp"; echo $sp; echo "&nbsp"; echo "dan"; echo "&nbsp"; echo $p; echo"&nbsp"; echo "itu"; echo "&nbsp"; echo $sq;
    }
    else{
    	echo "Anda belum memilih pertanyaan logikanya";
    }
